FROM node:14.17.6-buster as build
WORKDIR /app 

COPY . .
COPY ["package.json", "package-lock.json*", "./"]
RUN npm ci --production
RUN npm run build

FROM nginx:1.12-alpine as prod
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]